---

version: '3'

services:
  santa-server:
    build:
      context: ..
      dockerfile: docker/DockerfileServer
    volumes:
      - "../data:/etc/data"


  santa-web:
    build:
      context: ..
      dockerfile: docker/DockerfileWeb
    ports:
      - "80:80"
      - "8080:8080"